version: '3'
services:
        graphql:
                build: ./rtdash/
                links:
                        - redis
                environment:
                        - REDIS_URL=redis://cache
                        - REDIS_HOST=redis
                        - REDIS_PORT=6379
                ports:
                        - "4000:4000"
        redis:
                image: "redis:alpine"
                container_name: cache
                expose:
                        - 6379
        web:
                build: ./rtdash_client/
                links:
                        - graphql
                ports:
                        - "80:8080"
                environment:
                        - NODE_ENV=production
                        - PORT=8080